### PR TITLE
Support tuple-like objects, support int coordinates

### PR DESCRIPTION
**Pull request by kerrick-lyft**
Allow the user to pass an array of tuple-like objects (i.e. objects that can be
passed to tuple()) instead of normal tuples. For example, if the user defines
a class Point, they can call

    vw.simplify([Point(1, 2), Point(3, 4), ...])

Also support points with integer coordinates, by casting the input coordinates
to floats.

### CODE REVIEW

**Comment by kerrick-lyft** [comment]
I'm working on adding tests.

**Comment by kerrick-lyft** [comment]
Added tests, can you take a look? Thanks!

**Comment by fitnr** [comment]
This seems good, but I'm going to check on the strange syntax failure in the tests before merging. It may be a day or two before I have time.

**Comment by kerrick-lyft** [comment]
Hey! Just pinging this

**Comment by kerrick-lyft** [comment]
Hey Neil, do you have time to look at this PR?

**Comment by fitnr** [comment]
This is merged, see f16908103.
Thanks for the addition, I've published a new release, v0.1.2, that contains this update.

**Pull request closed without merging**
